use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use chrono::DateTime;
use chrono::Utc;
use codex_app_server_protocol::CodexErrorInfo;
use codex_app_server_protocol::ThreadTimelineEntry;
use codex_protocol::SanitizedGitUrl;
use codex_protocol::SessionId;
use codex_protocol::ThreadId;
use codex_protocol::capabilities::SelectedCapabilityRoot;
use codex_protocol::dynamic_tools::DynamicToolSpec;
use codex_protocol::models::BaseInstructions;
use codex_protocol::models::PermissionProfile;
use codex_protocol::openai_models::ReasoningEffort;
use codex_protocol::protocol::AskForApproval;
use codex_protocol::protocol::EventMsg;
use codex_protocol::protocol::GitInfo;
use codex_protocol::protocol::HistoryPosition;
use codex_protocol::protocol::MultiAgentVersion;
use codex_protocol::protocol::RolloutReferenceItem;
use codex_protocol::protocol::SessionMetaLine;
use codex_protocol::protocol::SessionSource;
use codex_protocol::protocol::ThreadHistoryMode;
use codex_protocol::protocol::ThreadMemoryMode as MemoryMode;
use codex_protocol::protocol::ThreadRolledBackEvent;
use codex_protocol::protocol::ThreadSource;
use codex_protocol::protocol::TokenUsage;
use codex_rollout::ResponseItemEnvelope;
use codex_rollout::RolloutItem;
use serde::Deserialize;
use serde::Deserializer;
use serde::Serialize;
use serde::Serializer;

use crate::ThreadStoreError;

mod optional_option {
    use super::*;

    pub fn serialize<T, S>(value: &Option<Option<T>>, serializer: S) -> Result<S::Ok, S::Error>
    where
        T: Serialize,
        S: Serializer,
    {
        match value {
            Some(value) => value.serialize(serializer),
            None => serializer.serialize_none(),
        }
    }

    pub fn deserialize<'de, T, D>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
    where
        T: Deserialize<'de>,
        D: Deserializer<'de>,
    {
        Option::<T>::deserialize(deserializer).map(Some)
    }
}

/// Thread-scoped metadata used when opening live persistence.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThreadPersistenceMetadata {
    /// Effective working directory for environment-backed threads.
    ///
    /// `None` means the thread has no filesystem/environment context.
    pub cwd: Option<PathBuf>,
    /// Model provider associated with the thread.
    pub model_provider: String,
    /// Memory mode associated with the live thread.
    pub memory_mode: MemoryMode,
}

/// Extra configuration fields for a thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExtraConfig {}

/// Parameters required to create a persisted thread.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CreateThreadParams {
    /// Session id shared by the root thread and all of its subagents.
    pub session_id: SessionId,
    /// Thread id generated by Codex before opening persistence.
    pub thread_id: ThreadId,
    /// Optional extra configuration fields for the thread.
    pub extra_config: Option<ExtraConfig>,
    /// Source thread id when this thread is created as a fork.
    pub forked_from_id: Option<ThreadId>,
    /// Exclusive ordinal inherited from the logical fork parent, independent of physical ancestry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub forked_from_ordinal_exclusive: Option<u64>,
    /// The ID of the parent thread. This will only be set if this thread is a subagent.
    pub parent_thread_id: Option<ThreadId>,
    /// Runtime source for the thread.
    pub source: SessionSource,
    /// Optional analytics source classification for this thread.
    pub thread_source: Option<ThreadSource>,
    /// Effective originator used for this thread's Responses requests and analytics events.
    pub originator: String,
    /// Base instructions persisted in session metadata.
    pub base_instructions: BaseInstructions,
    /// Dynamic tools available to the thread at startup.
    pub dynamic_tools: Vec<DynamicToolSpec>,
    /// Environment-qualified capability roots selected for this thread.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub selected_capability_roots: Vec<SelectedCapabilityRoot>,
    /// Multi-agent runtime selected when the thread was created.
    pub multi_agent_version: Option<MultiAgentVersion>,
    /// Persisted thread history contract selected when the thread was created.
    pub history_mode: ThreadHistoryMode,
    /// Exclusive prefix of another paginated rollout inherited by this thread.
    pub history_base: Option<HistoryPosition>,
    /// First rollout ordinal that belongs to this subagent's projected history.
    pub subagent_history_start_ordinal: Option<u64>,
    /// Controls when a newly created thread becomes durable.
    #[serde(default)]
    pub persistence_mode: ThreadPersistenceMode,
    /// First lineage-relative ordinal written to a new paginated rollout.
    ///
    /// Full-history forks continue after their immutable inherited prefix. Legacy rollouts ignore
    /// this value.
    #[serde(default)]
    pub initial_rollout_ordinal: u64,
    /// Initial context-window identity captured when the thread was created.
    pub initial_window_id: String,
    /// Metadata captured for the newly created thread.
    pub metadata: ThreadPersistenceMetadata,
}

/// Persistence policy for a newly created live thread.
///
/// Deferred threads use the rollout recorder's canonical in-memory queue until an explicit
/// persist or local segment freeze. Materialization is a one-way transition shared by every clone
/// of the live thread.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadPersistenceMode {
    /// Append, flush, and metadata behavior remains durable as normal.
    #[default]
    Durable,
    /// Append and flush remain pathless until persist or local segment freeze.
    Deferred,
}

/// Parameters required to reopen persistence for an existing thread.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ResumeThreadParams {
    /// Existing thread id whose future items should be appended.
    pub thread_id: ThreadId,
    /// Known local rollout path when the caller resumed from a specific file.
    pub rollout_path: Option<PathBuf>,
    /// Known replay history for the resumed thread, if already loaded by the caller.
    pub history: Option<Arc<Vec<RolloutItem>>>,
    /// Whether archived threads may be reopened.
    pub include_archived: bool,
    /// Metadata for future writes appended to the resumed live thread.
    pub metadata: ThreadPersistenceMetadata,
}

pub(crate) fn canonical_history_mode_from_rollout_items(
    items: &[RolloutItem],
) -> ThreadHistoryMode {
    // A reference-backed fork keeps only its own canonical SessionMeta in the child rollout. Older
    // copied-history forks can still contain additional source metadata, so the first item remains
    // authoritative for both representations.
    items
        .iter()
        .find_map(|item| match item {
            RolloutItem::SessionMeta(meta_line) => Some(meta_line.meta.history_mode),
            _ => None,
        })
        .unwrap_or_default()
}

/// Parameters for appending rollout items to a live thread.
#[derive(Clone, Debug)]
pub struct AppendThreadItemsParams {
    /// Thread id to append to.
    pub thread_id: ThreadId,
    /// Raw rollout items to append in order.
    ///
    /// Store implementations are responsible for applying the shared rollout persistence policy
    /// before writing durable replay history or any implementation-owned projections.
    pub items: Vec<RolloutItem>,
}

/// Parameters for freezing a local rollout prefix.
#[derive(Clone, Debug)]
pub struct FreezeRolloutSegmentParams {
    mode: FreezeRolloutSegmentMode,
    initial_items: Vec<RolloutItem>,
    certified_checkpoint_start: Option<usize>,
}

/// Authoritative result of persisting one segment-state checkpoint.
///
/// `NotCommitted` guarantees that no checkpoint item became durable. `Indeterminate` means the
/// store cannot prove whether the checkpoint became authoritative, so the live thread must reject
/// later persistence until it is reopened from durable history.
#[derive(Debug)]
pub enum SegmentCheckpointPersistenceOutcome {
    /// The complete checkpoint is durable and authoritative.
    Committed,
    /// No checkpoint item became durable.
    NotCommitted { error: ThreadStoreError },
    /// The store cannot determine whether the checkpoint became authoritative.
    Indeterminate { error: ThreadStoreError },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum FreezeRolloutSegmentMode {
    Snapshot,
    Rotate,
}

impl FreezeRolloutSegmentParams {
    /// Creates an immutable snapshot without replacing the source rollout.
    pub fn snapshot() -> Self {
        Self {
            mode: FreezeRolloutSegmentMode::Snapshot,
            initial_items: Vec::new(),
            certified_checkpoint_start: None,
        }
    }

    /// Rotates the source rollout and writes `initial_items` after its reference.
    pub fn rotate(initial_items: Vec<RolloutItem>) -> Self {
        Self {
            mode: FreezeRolloutSegmentMode::Rotate,
            initial_items,
            certified_checkpoint_start: None,
        }
    }

    /// Rotates the source rollout and writes a certified current-state checkpoint after its
    /// predecessor reference.
    pub fn rotate_checkpoint(checkpoint: codex_rollout::CertifiedSegmentStateCheckpoint) -> Self {
        Self {
            mode: FreezeRolloutSegmentMode::Rotate,
            initial_items: checkpoint.into_items(),
            certified_checkpoint_start: Some(0),
        }
    }

    /// Rotates the source rollout and publishes one rollback marker with the certified state that
    /// results from applying it. The marker and checkpoint share one atomic publication.
    pub fn rotate_after_rollback(
        rollback: ThreadRolledBackEvent,
        checkpoint: codex_rollout::CertifiedSegmentStateCheckpoint,
    ) -> Self {
        let mut initial_items = Vec::with_capacity(checkpoint.items().len() + 1);
        initial_items.push(RolloutItem::EventMsg(EventMsg::ThreadRolledBack(rollback)));
        initial_items.extend(checkpoint.into_items());
        Self {
            mode: FreezeRolloutSegmentMode::Rotate,
            initial_items,
            certified_checkpoint_start: Some(1),
        }
    }

    pub(crate) fn is_snapshot(&self) -> bool {
        matches!(self.mode, FreezeRolloutSegmentMode::Snapshot)
    }

    pub(crate) fn initial_items(&self) -> &[RolloutItem] {
        self.initial_items.as_slice()
    }

    pub(crate) fn validate_checkpoint(
        &self,
    ) -> Result<(), codex_rollout::SegmentStateCheckpointError> {
        let Some(checkpoint_start) = self.certified_checkpoint_start else {
            #[cfg(test)]
            return Ok(());
            #[cfg(not(test))]
            return Err(codex_rollout::SegmentStateCheckpointError::uncertified());
        };
        codex_rollout::validate_certified_segment_state_checkpoint(
            &self.initial_items[checkpoint_start..],
        )
    }
}

/// Immutable rollout prefix produced by [`crate::LocalThreadStore::freeze_thread_segment`].
///
/// Segmentation shares immutable inherited history across full-history forks and bounds the
/// mutable live rollout after compaction. It is independent of [`ThreadHistoryMode`] and is not a
/// legacy compatibility mechanism.
#[derive(Clone, Debug)]
pub struct FrozenRolloutSegment {
    /// Reference to the immutable source prefix.
    pub reference: RolloutReferenceItem,
    /// Native upstream pointer to the same immutable prefix for paginated history.
    pub history_base: Option<HistoryPosition>,
    /// Canonical metadata line copied from the source segment before it was frozen.
    pub source_session_meta: SessionMetaLine,
    /// Persisted history mode inherited by continuations and full-history forks.
    pub history_mode: ThreadHistoryMode,
    /// First lineage-relative ordinal available after the frozen prefix.
    pub next_rollout_ordinal: Option<u64>,
}

/// Parameters for loading persisted history for resume, fork, rollback, and memory jobs.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoadThreadHistoryParams {
    /// Thread id to load.
    pub thread_id: ThreadId,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
}

/// Persisted rollout history for a thread, without any filesystem path requirement.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredThreadHistory {
    /// Thread id represented by the history.
    pub thread_id: ThreadId,
    /// Persisted rollout items in replay order.
    pub items: Vec<RolloutItem>,
}

/// Persisted rollout items needed to reconstruct the latest model-visible context.
///
/// Local stores may return only a resumable suffix while stores without targeted reads may return
/// the full persisted history. In either case, `items` remain in replay order and are suitable for
/// the existing rollout reconstruction path.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredModelContext {
    /// Thread id represented by the model context.
    pub thread_id: ThreadId,
    /// Persisted rollout items in replay order.
    pub items: Vec<RolloutItem>,
}

/// Requested boundary for inheriting a paginated thread's history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ForkBoundary {
    /// Inherit the source thread's latest durable state.
    Latest,
    /// Inherit history through the newest visible occurrence of this turn.
    ThroughTurn(String),
    /// Inherit history preceding the original visible occurrence of this turn.
    BeforeTurn(String),
}

/// Parameters for freezing the source history used to initialize a fork.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PrepareForkParams {
    /// Immediate source thread whose metadata and approval settings are inherited.
    pub thread_id: ThreadId,
    /// Requested inclusive or exclusive fork boundary.
    pub boundary: ForkBoundary,
}

/// Parameters for reverting a paginated thread's durable history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RevertThreadParams {
    /// Stable logical thread to revert.
    pub thread_id: ThreadId,
    /// First turn excluded from the retained history.
    pub before_turn_id: String,
}

/// Frozen source history and model context for a reference-backed fork.
#[derive(Debug)]
pub struct PreparedFork {
    /// Immediate source thread, even when the normalized history base names an ancestor.
    pub source_thread_id: ThreadId,
    /// Compatibility position selected while normalizing the paginated lineage.
    pub history_base: Option<HistoryPosition>,
    /// Canonical immutable rollout prefix inherited by a durable child.
    ///
    /// Context-only ephemeral forks do not persist a child rollout, so they retain the bounded
    /// model context instead of freezing the source rollout.
    pub frozen_segment: Option<FrozenRolloutSegment>,
    /// Bounded model context selected by the requested fork boundary.
    pub model_context: Arc<Vec<RolloutItem>>,
    /// Latest source context used for settings that follow the source thread rather than the
    /// selected history boundary.
    pub latest_model_context: Arc<Vec<RolloutItem>>,
    /// Complete logical history selected by the requested fork boundary.
    pub response_history: Arc<Vec<RolloutItem>>,
    /// Complete logical history that must be copied because a `history_base` edge cannot be
    /// represented by the frozen segment reference.
    pub copied_history: Option<Arc<Vec<RolloutItem>>>,
    /// Complete projected parent turns when indexed fork preparation avoids JSONL replay.
    pub projected_response_turns: Option<Arc<Vec<StoredTurn>>>,
    /// Authoritative copy-on-write model history retained without copying parent response items.
    pub shared_model_response_items: Option<Arc<Vec<ResponseItemEnvelope>>>,
    /// Whether a latest-state fork should synthesize an interruption for an open turn.
    pub interrupt_if_open: bool,
    /// Blocks source deletion until the child's history reference is durable.
    _source_reservation: Box<dyn std::fmt::Debug + Send>,
}

/// Shared source-thread lease held while a child rollout reference is becoming durable.
#[derive(Debug)]
pub struct ThreadLifecycleReservation {
    _guard: tokio::sync::OwnedRwLockReadGuard<()>,
}

impl ThreadLifecycleReservation {
    pub(crate) fn new(guard: tokio::sync::OwnedRwLockReadGuard<()>) -> Self {
        Self { _guard: guard }
    }
}

impl PreparedFork {
    /// Creates a frozen fork snapshot while retaining a backend-owned source reservation.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        source_thread_id: ThreadId,
        history_base: Option<HistoryPosition>,
        frozen_segment: Option<FrozenRolloutSegment>,
        model_context: Arc<Vec<RolloutItem>>,
        latest_model_context: Arc<Vec<RolloutItem>>,
        response_history: Arc<Vec<RolloutItem>>,
        interrupt_if_open: bool,
        source_reservation: impl std::fmt::Debug + Send + 'static,
    ) -> Self {
        Self {
            source_thread_id,
            history_base,
            frozen_segment,
            model_context,
            latest_model_context,
            response_history,
            copied_history: None,
            projected_response_turns: None,
            shared_model_response_items: None,
            interrupt_if_open,
            _source_reservation: Box::new(source_reservation),
        }
    }
}

/// Parameters for reading a thread summary and optionally its replay history.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReadThreadParams {
    /// Thread id to read.
    pub thread_id: ThreadId,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
    /// Whether persisted rollout items should be included in the response.
    pub include_history: bool,
}

/// Parameters for reading persisted metadata for a bounded set of threads.
///
/// Missing thread IDs are omitted. Implementations must not load thread history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ReadThreadsParams {
    /// Thread IDs to look up. Results preserve this order after missing IDs are omitted.
    pub thread_ids: Vec<ThreadId>,
}

/// Parameters for reading a local rollout-backed thread by path.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReadThreadByRolloutPathParams {
    /// Local rollout JSONL path to read.
    pub rollout_path: PathBuf,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
    /// Whether persisted rollout items should be included in the response.
    pub include_history: bool,
}

/// The sort key to use when listing stored threads.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadSortKey {
    /// Sort by the thread creation timestamp.
    #[default]
    CreatedAt,
    /// Sort by the thread last-update timestamp.
    UpdatedAt,
    /// Sort by the thread's product recency timestamp.
    RecencyAt,
    /// Sort by the thread's persisted position within its section.
    SectionPosition,
}

/// The direction to use when listing stored threads.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum SortDirection {
    /// Return older threads before newer threads.
    Asc,
    /// Return newer threads before older threads.
    #[default]
    Desc,
}

/// Spawn-graph relationship used to filter thread listings.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadRelationFilter {
    /// Return only threads whose immediate parent is the given thread.
    DirectChildrenOf(ThreadId),
    /// Return every thread transitively descended from the given thread.
    DescendantsOf(ThreadId),
}

/// Parameters for listing threads.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListThreadsParams {
    /// Maximum number of threads to return.
    pub page_size: usize,
    /// Opaque cursor returned by a previous list call.
    pub cursor: Option<String>,
    /// Sort order requested by the caller.
    pub sort_key: ThreadSortKey,
    /// Sort direction requested by the caller.
    pub sort_direction: SortDirection,
    /// Allowed session sources. Empty means implementation default.
    pub allowed_sources: Vec<SessionSource>,
    /// Optional model provider filter. `None` means implementation default, while an empty vector
    /// means all providers.
    pub model_providers: Option<Vec<String>>,
    /// Optional cwd filters. `None` means all working directories, while an empty vector matches no
    /// threads.
    pub cwd_filters: Option<Vec<PathBuf>>,
    /// Omit to include every section, set to `None` to match unsectioned
    /// threads, or provide a section ID to match that section.
    pub section: Option<Option<String>>,
    /// Omit to include every project, set to None for unassigned threads,
    /// or provide a project ID to match that project.
    pub project_id: ClearableField<String>,
    /// Whether archived threads should be listed instead of active threads.
    pub archived: bool,
    /// Optional substring/full-text search term for thread title/preview.
    pub search_term: Option<String>,
    /// Optional spawn-graph relationship filter.
    pub relation_filter: Option<ThreadRelationFilter>,
    /// Return directly from the state DB without scanning JSONL rollouts to repair metadata.
    pub use_state_db_only: bool,
}

/// Parameters for searching thread content.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchThreadsParams {
    /// Maximum number of threads to return.
    pub page_size: usize,
    /// Opaque cursor returned by a previous search call.
    pub cursor: Option<String>,
    /// Sort order requested by the caller.
    pub sort_key: ThreadSortKey,
    /// Sort direction requested by the caller.
    pub sort_direction: SortDirection,
    /// Allowed session sources. Empty means implementation default.
    pub allowed_sources: Vec<SessionSource>,
    /// Whether archived threads should be searched instead of active threads.
    pub archived: bool,
    /// Visible thread content to search for.
    pub search_term: String,
}

/// A page of stored thread records.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ThreadPage {
    /// Threads returned for this page.
    pub items: Vec<StoredThread>,
    /// Opaque cursor to continue listing.
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredThreadSearchResult {
    pub thread: StoredThread,
    pub snippet: String,
}

/// A page of thread-search results.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ThreadSearchPage {
    /// Search results returned for this page.
    pub items: Vec<StoredThreadSearchResult>,
    /// Opaque cursor to continue searching.
    pub next_cursor: Option<String>,
}

/// Requested amount of item detail for stored turns.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum StoredTurnItemsView {
    /// Return turn metadata only.
    NotLoaded,
    /// Return display summary items for each turn.
    #[default]
    Summary,
}

/// Store-owned status for a persisted turn.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum StoredTurnStatus {
    /// The turn completed normally.
    Completed,
    /// The turn was interrupted before normal completion.
    Interrupted,
    /// The turn failed.
    Failed,
    /// The turn is still in progress.
    InProgress,
}

/// Store-owned error details for a failed persisted turn.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StoredTurnError {
    /// User-visible error message.
    pub message: String,
    /// Structured Codex error classification, when available.
    pub codex_error_info: Option<CodexErrorInfo>,
    /// Optional additional detail for clients that expose expanded error context.
    pub additional_details: Option<String>,
}

/// Parameters for listing turns within a stored thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListTurnsParams {
    /// Thread id to read.
    pub thread_id: ThreadId,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
    /// Opaque cursor returned by a previous list call.
    pub cursor: Option<String>,
    /// Maximum number of turns to return.
    pub page_size: usize,
    /// Sort direction requested by the caller.
    pub sort_direction: SortDirection,
    /// Requested amount of item detail for each returned turn.
    pub items_view: StoredTurnItemsView,
}

/// Store-owned turn representation used by turn pagination APIs.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredTurn {
    /// Turn id.
    pub turn_id: String,
    /// Projected app-server item snapshots associated with this turn, according to `items_view`.
    pub items: Vec<StoredThreadItem>,
    /// Amount of item detail included in `items`.
    pub items_view: StoredTurnItemsView,
    /// Store-owned status for API layer projection.
    pub status: StoredTurnStatus,
    /// Error message when the turn failed.
    pub error: Option<StoredTurnError>,
    /// Unix timestamp (seconds) when the turn started.
    pub started_at: Option<i64>,
    /// Unix timestamp (seconds) when the turn completed.
    pub completed_at: Option<i64>,
    /// Duration between turn start and completion in milliseconds, if known.
    pub duration_ms: Option<i64>,
}

/// A page of stored turns.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TurnPage {
    /// Turns returned for this page.
    pub turns: Vec<StoredTurn>,
    /// Opaque cursor to continue listing.
    pub next_cursor: Option<String>,
    /// Opaque cursor for fetching in the opposite direction.
    pub backwards_cursor: Option<String>,
}

/// Parameters for listing persisted items within a thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListItemsParams {
    /// Thread id to read.
    pub thread_id: ThreadId,
    /// Optional turn id to filter by. When omitted, returns items across the thread.
    pub turn_id: Option<String>,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
    /// Opaque cursor returned by a previous list call.
    pub cursor: Option<String>,
    /// Maximum number of items to return.
    pub page_size: usize,
    /// Direction to sort items by the selected ordinal.
    pub sort_direction: SortDirection,
    /// Ordinal to sort items by. Update-ordinal sorting requires an update watermark.
    pub sort_key: ItemSortKey,
    /// Filters out items with an update ordinal less than or equal to the provided value.
    pub after_updated_at_ordinal: Option<u64>,
}

/// The ordinal to use when listing persisted items.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ItemSortKey {
    /// Sort by the ordinal where the item was first projected.
    CreatedAtOrdinal,
    /// Sort by the ordinal where the item was last updated.
    UpdatedAtOrdinal,
}

/// A projected app-server `ThreadItem` snapshot within a turn.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct StoredThreadItem {
    /// Turn containing this item.
    pub turn_id: String,
    /// Stable item identifier within the turn.
    pub item_id: String,
    /// Rollout ordinal of the latest persisted update to this item.
    pub updated_at_ordinal: u64,
    /// Unix timestamp (milliseconds) when this logical item was first projected.
    pub created_at_ms: i64,
    /// Serialized app-server ThreadItem snapshot.
    pub item_json: Vec<u8>,
}

/// A page of persisted items within a thread, optionally filtered to a turn.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ItemPage {
    /// Items returned for this page.
    pub items: Vec<StoredThreadItem>,
    /// Opaque cursor to continue listing.
    pub next_cursor: Option<String>,
    /// Opaque cursor for fetching in the opposite direction.
    pub backwards_cursor: Option<String>,
}

/// Parameters for reading a bounded mixed thread timeline.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ListTimelineParams {
    pub thread_id: ThreadId,
    pub cursor: Option<String>,
    pub page_size: usize,
}

/// Ordinary items, realtime facts, and the session state preceding their page.
#[derive(Clone, Debug, PartialEq)]
pub struct TimelinePage {
    pub items: Vec<ThreadTimelineEntry>,
    pub next_cursor: Option<String>,
    pub active_realtime_session_at_page_start: Option<String>,
}

/// Parameters for searching visible message occurrences within one paginated thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchThreadOccurrencesParams {
    /// Thread id to search.
    pub thread_id: ThreadId,
    /// Case-insensitive literal substring to find.
    pub search_term: String,
    /// Opaque cursor returned by a previous search call.
    pub cursor: Option<String>,
    /// Maximum number of occurrences to return.
    pub page_size: usize,
}

/// UTF-16 code-unit range within `snippet`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SearchTextRange {
    pub start: u32,
    pub end: u32,
}

/// One visible message occurrence within a stored thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct StoredThreadOccurrence {
    pub turn_id: String,
    pub item_id: String,
    pub snippet: String,
    pub snippet_match_range: SearchTextRange,
    /// Inclusive cursor accepted by `thread/turns/list` for this turn.
    pub turn_cursor: String,
}

/// A page of visible message occurrences within one stored thread.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ThreadOccurrenceSearchPage {
    pub items: Vec<StoredThreadOccurrence>,
    pub next_cursor: Option<String>,
}

/// Store-owned thread metadata used by list/read/resume responses.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StoredThread {
    /// Thread id.
    pub thread_id: ThreadId,
    /// Optional extra configuration fields for the thread.
    pub extra_config: Option<ExtraConfig>,
    /// Local rollout path when the backing store is filesystem-based.
    pub rollout_path: Option<PathBuf>,
    /// Source thread id when this thread was forked from another thread.
    pub forked_from_id: Option<ThreadId>,
    /// The ID of the parent thread. This will only be set if this thread is a subagent.
    pub parent_thread_id: Option<ThreadId>,
    /// Best available user-facing preview, usually the first user message.
    pub preview: String,
    /// Optional user-facing thread name/title.
    pub name: Option<String>,
    /// Model provider id associated with the thread.
    pub model_provider: String,
    /// Latest observed model, if known.
    pub model: Option<String>,
    /// Latest observed reasoning effort, if known.
    pub reasoning_effort: Option<ReasoningEffort>,
    /// Thread creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Thread last-update timestamp.
    pub updated_at: DateTime<Utc>,
    /// Thread product-recency timestamp.
    pub recency_at: DateTime<Utc>,
    /// Thread archive timestamp, if archived.
    pub archived_at: Option<DateTime<Utc>>,
    /// The user-selected section for this thread, if any.
    pub section: Option<codex_state::ThreadSection>,
    /// The server-owned ordering position within the thread's section.
    #[serde(default)]
    pub section_position: Option<i64>,
    /// The time when the thread most recently entered its current section.
    #[serde(default)]
    pub section_entered_at: Option<DateTime<Utc>>,
    /// Canonical project assignment owned by app-server, if any.
    #[serde(default)]
    pub project_id: Option<String>,
    /// Working directory captured for the thread.
    pub cwd: PathBuf,
    /// CLI version captured for the thread.
    pub cli_version: String,
    /// Runtime source for the thread.
    pub source: SessionSource,
    /// Persisted thread history contract selected when this thread was created.
    pub history_mode: ThreadHistoryMode,
    /// Optional analytics source classification for this thread.
    pub thread_source: Option<ThreadSource>,
    /// Optional random nickname for thread-spawn sub-agents.
    pub agent_nickname: Option<String>,
    /// Optional role for thread-spawn sub-agents.
    pub agent_role: Option<String>,
    /// Optional canonical path for thread-spawn sub-agents.
    pub agent_path: Option<String>,
    /// Optional Git metadata captured for the thread.
    pub git_info: Option<GitInfo>,
    /// Approval mode captured for the thread.
    pub approval_mode: AskForApproval,
    /// Canonical runtime permissions captured for the thread.
    pub permission_profile: PermissionProfile,
    /// Last observed token usage.
    pub token_usage: Option<TokenUsage>,
    /// First user message observed for this thread, if any.
    pub first_user_message: Option<String>,
    /// Persisted history, populated only when requested.
    pub history: Option<StoredThreadHistory>,
}

/// Optional field patch where omission leaves a value unchanged and `Some(None)` clears it.
pub type ClearableField<T> = Option<Option<T>>;

/// Patch for thread Git metadata.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GitInfoPatch {
    /// Replacement commit SHA, clear request, or no-op.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub sha: ClearableField<String>,
    /// Replacement branch name, clear request, or no-op.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub branch: ClearableField<String>,
    /// Replacement origin URL, clear request, or no-op.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub origin_url: ClearableField<SanitizedGitUrl>,
}

impl GitInfoPatch {
    /// Merges another patch into this one using field-presence semantics.
    ///
    /// Omitted fields in `next` leave the current patch unchanged. Present fields replace the
    /// current value, including clear requests like `Some(None)`.
    pub fn merge(&mut self, next: Self) {
        if next.sha.is_some() {
            self.sha = next.sha;
        }
        if next.branch.is_some() {
            self.branch = next.branch;
        }
        if next.origin_url.is_some() {
            self.origin_url = next.origin_url;
        }
    }
}

/// Patch for thread metadata.
///
/// Every field is literal: `None` leaves that field unchanged, while `Some`
/// applies the supplied value. Fields whose value may itself be cleared use an
/// inner `Option`, where `Some(None)` clears the field.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ThreadMetadataPatch {
    /// Replacement user-facing thread name.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub name: ClearableField<String>,
    /// Known local rollout path for stores that expose one.
    pub rollout_path: Option<PathBuf>,
    /// Best available preview text for discovery/listing.
    pub preview: Option<String>,
    /// Best-effort title derived from history.
    pub title: Option<String>,
    /// Model provider associated with the thread.
    pub model_provider: Option<String>,
    /// Latest observed model.
    pub model: Option<String>,
    /// Latest observed reasoning effort.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub reasoning_effort: ClearableField<ReasoningEffort>,
    /// Creation timestamp when known.
    pub created_at: Option<DateTime<Utc>>,
    /// Last update timestamp for this metadata observation.
    pub updated_at: Option<DateTime<Utc>>,
    /// Advance product recency to at least this timestamp.
    pub advance_recency_at: Option<DateTime<Utc>>,
    /// Session source.
    pub source: Option<SessionSource>,
    /// Optional analytics source classification.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub thread_source: ClearableField<ThreadSource>,
    /// Optional agent nickname.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub agent_nickname: ClearableField<String>,
    /// Optional agent role.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub agent_role: ClearableField<String>,
    /// Optional canonical agent path.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub agent_path: ClearableField<String>,
    /// Working directory.
    pub cwd: Option<PathBuf>,
    /// CLI version that created the thread.
    pub cli_version: Option<String>,
    /// Approval mode.
    pub approval_mode: Option<AskForApproval>,
    /// Canonical runtime permissions.
    pub permission_profile: Option<PermissionProfile>,
    /// Last observed token usage.
    pub token_usage: Option<TokenUsage>,
    /// First user message observed for this thread.
    pub first_user_message: Option<String>,
    /// Git metadata patch.
    pub git_info: Option<GitInfoPatch>,
    /// Thread memory behavior.
    pub memory_mode: Option<MemoryMode>,
    /// Initial project assignment supplied with thread creation.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "optional_option"
    )]
    pub project_id: ClearableField<String>,
}

impl ThreadMetadataPatch {
    /// Merges another patch into this one using field-presence semantics.
    ///
    /// Omitted fields in `next` leave the current patch unchanged. Present fields replace the
    /// current value, including clear requests like `Some(None)`. Nested patches use the same
    /// semantics.
    pub fn merge(&mut self, next: Self) {
        if next.name.is_some() {
            self.name = next.name;
        }
        if next.rollout_path.is_some() {
            self.rollout_path = next.rollout_path;
        }
        if next.preview.is_some() {
            self.preview = next.preview;
        }
        if next.title.is_some() {
            self.title = next.title;
        }
        if next.model_provider.is_some() {
            self.model_provider = next.model_provider;
        }
        if next.model.is_some() {
            self.model = next.model;
        }
        if next.reasoning_effort.is_some() {
            self.reasoning_effort = next.reasoning_effort;
        }
        if next.created_at.is_some() {
            self.created_at = next.created_at;
        }
        if next.updated_at.is_some() {
            self.updated_at = next.updated_at;
        }
        if next.advance_recency_at.is_some() {
            self.advance_recency_at = next.advance_recency_at;
        }
        if next.source.is_some() {
            self.source = next.source;
        }
        if next.thread_source.is_some() {
            self.thread_source = next.thread_source;
        }
        if next.agent_nickname.is_some() {
            self.agent_nickname = next.agent_nickname;
        }
        if next.agent_role.is_some() {
            self.agent_role = next.agent_role;
        }
        if next.agent_path.is_some() {
            self.agent_path = next.agent_path;
        }
        if next.cwd.is_some() {
            self.cwd = next.cwd;
        }
        if next.cli_version.is_some() {
            self.cli_version = next.cli_version;
        }
        if next.approval_mode.is_some() {
            self.approval_mode = next.approval_mode;
        }
        if next.permission_profile.is_some() {
            self.permission_profile = next.permission_profile;
        }
        if next.token_usage.is_some() {
            self.token_usage = next.token_usage;
        }
        if next.first_user_message.is_some() {
            self.first_user_message = next.first_user_message;
        }
        if let Some(git_info) = next.git_info {
            self.git_info
                .get_or_insert_with(GitInfoPatch::default)
                .merge(git_info);
        }
        if next.memory_mode.is_some() {
            self.memory_mode = next.memory_mode;
        }
        if next.project_id.is_some() {
            self.project_id = next.project_id;
        }
    }

    pub fn is_empty(&self) -> bool {
        self.name.is_none()
            && self.rollout_path.is_none()
            && self.preview.is_none()
            && self.title.is_none()
            && self.model_provider.is_none()
            && self.model.is_none()
            && self.reasoning_effort.is_none()
            && self.created_at.is_none()
            && self.updated_at.is_none()
            && self.advance_recency_at.is_none()
            && self.source.is_none()
            && self.thread_source.is_none()
            && self.agent_nickname.is_none()
            && self.agent_role.is_none()
            && self.agent_path.is_none()
            && self.cwd.is_none()
            && self.cli_version.is_none()
            && self.approval_mode.is_none()
            && self.permission_profile.is_none()
            && self.token_usage.is_none()
            && self.first_user_message.is_none()
            && self.git_info.is_none()
            && self.memory_mode.is_none()
            && self.project_id.is_none()
    }
}

/// Parameters for patching mutable thread metadata.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct UpdateThreadMetadataParams {
    /// Thread id to update.
    pub thread_id: ThreadId,
    /// Patch to apply.
    pub patch: ThreadMetadataPatch,
    /// Whether archived threads are eligible.
    pub include_archived: bool,
}

/// Parameters for advancing a visible root thread after descendant activity.
#[derive(Clone, Copy, Debug)]
pub struct TouchRootThreadRecencyParams {
    /// Spawned descendant whose activity should make its root visible.
    pub descendant_thread_id: ThreadId,
    /// Timestamp of the observed descendant activity.
    pub activity_at: DateTime<Utc>,
    /// Minimum time between persisted root recency advances.
    pub minimum_interval: Duration,
}

/// Parameters for moving a thread to, within, or out of a server-ordered section.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MoveThreadToSectionParams {
    /// Thread to move.
    pub thread_id: ThreadId,
    /// Destination section, or `None` to remove the thread from its section.
    pub section: Option<String>,
    /// Existing section member to insert before, or `None` to append.
    pub before_thread_id: Option<ThreadId>,
}

/// Parameters for archiving or unarchiving a thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArchiveThreadParams {
    /// Thread id to archive or unarchive.
    pub thread_id: ThreadId,
}

/// Parameters for archiving a set of threads as one store operation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArchiveThreadsParams {
    /// Thread ids to archive, in the order their persisted data should be moved.
    pub thread_ids: Vec<ThreadId>,
    /// Thread ids whose paginated writer ownership must be checked before archiving, including
    /// descendants whose rollout has not materialized yet.
    #[serde(default)]
    pub writer_lock_thread_ids: Vec<ThreadId>,
}

/// Parameters for deleting a thread.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeleteThreadParams {
    /// Thread id to delete.
    pub thread_id: ThreadId,
}

/// Parameters for deleting a set of threads as one store operation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeleteThreadsParams {
    /// Thread ids to delete, in the order their persisted data should be removed.
    pub thread_ids: Vec<ThreadId>,
}

/// Exact durable result of an ordered multi-thread deletion.
///
/// An error after earlier deletions is reported here so callers can reconcile those irreversible
/// deletions before returning the error to their client.
#[derive(Debug)]
pub struct DeleteThreadsOutcome {
    /// Thread IDs whose persisted rollout data was deleted or was already absent, in request order.
    pub deleted_thread_ids: Vec<ThreadId>,
    /// First deletion that failed after the completed prefix.
    pub failure: Option<DeleteThreadsFailure>,
}

/// First failed member of an ordered multi-thread deletion.
#[derive(Debug)]
pub struct DeleteThreadsFailure {
    /// Thread ID whose deletion failed.
    pub thread_id: ThreadId,
    /// Store error returned for `thread_id`.
    pub error: crate::ThreadStoreError,
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_eq;
    use serde_json::json;

    use super::*;

    #[test]
    fn thread_metadata_patch_round_trips_optional_clears() {
        let patch = ThreadMetadataPatch {
            name: Some(None),
            reasoning_effort: Some(None),
            thread_source: Some(None),
            agent_nickname: Some(None),
            agent_role: Some(None),
            agent_path: Some(None),
            ..Default::default()
        };

        let value = serde_json::to_value(&patch).expect("serialize patch");
        assert_eq!(value["name"], json!(null));
        assert_eq!(value["reasoning_effort"], json!(null));
        assert_eq!(value["thread_source"], json!(null));
        assert_eq!(value["agent_nickname"], json!(null));
        assert_eq!(value["agent_role"], json!(null));
        assert_eq!(value["agent_path"], json!(null));

        let decoded: ThreadMetadataPatch =
            serde_json::from_value(value).expect("deserialize patch");
        assert_eq!(decoded.name, Some(None));
        assert_eq!(decoded.reasoning_effort, Some(None));
        assert_eq!(decoded.thread_source, Some(None));
        assert_eq!(decoded.agent_nickname, Some(None));
        assert_eq!(decoded.agent_role, Some(None));
        assert_eq!(decoded.agent_path, Some(None));
    }

    #[test]
    fn git_info_patch_round_trips_optional_clears() {
        let patch = ThreadMetadataPatch {
            git_info: Some(GitInfoPatch {
                sha: None,
                branch: Some(Some("main".to_string())),
                origin_url: Some(None),
            }),
            ..Default::default()
        };

        let value = serde_json::to_value(&patch).expect("serialize patch");
        assert_eq!(
            value["git_info"],
            json!({
                "branch": "main",
                "origin_url": null,
            })
        );

        let decoded: ThreadMetadataPatch =
            serde_json::from_value(value).expect("deserialize patch");
        assert_eq!(
            decoded.git_info,
            Some(GitInfoPatch {
                sha: None,
                branch: Some(Some("main".to_string())),
                origin_url: Some(None),
            })
        );
    }

    #[test]
    fn thread_metadata_patch_accepts_missing_fields() {
        let decoded: ThreadMetadataPatch =
            serde_json::from_value(json!({})).expect("deserialize legacy patch");

        assert!(decoded.is_empty());
    }

    #[test]
    fn canonical_history_mode_uses_first_session_meta() {
        assert_eq!(
            canonical_history_mode_from_rollout_items(&[
                session_meta(ThreadHistoryMode::Legacy),
                session_meta(ThreadHistoryMode::Paginated),
            ]),
            ThreadHistoryMode::Legacy
        );
    }

    #[test]
    fn thread_metadata_patch_merge_uses_presence_semantics() {
        let mut current = ThreadMetadataPatch {
            name: Some(Some("old name".to_string())),
            preview: Some("old preview".to_string()),
            git_info: Some(GitInfoPatch {
                sha: Some(Some("abc123".to_string())),
                branch: Some(Some("main".to_string())),
                origin_url: None,
            }),
            ..Default::default()
        };

        current.merge(ThreadMetadataPatch {
            name: Some(None),
            preview: None,
            title: Some("new title".to_string()),
            git_info: Some(GitInfoPatch {
                sha: None,
                branch: Some(Some("feature".to_string())),
                origin_url: Some(None),
            }),
            ..Default::default()
        });

        assert_eq!(current.name, Some(None));
        assert_eq!(current.preview.as_deref(), Some("old preview"));
        assert_eq!(current.title.as_deref(), Some("new title"));
        assert_eq!(
            current.git_info,
            Some(GitInfoPatch {
                sha: Some(Some("abc123".to_string())),
                branch: Some(Some("feature".to_string())),
                origin_url: Some(None),
            })
        );
    }

    fn session_meta(history_mode: ThreadHistoryMode) -> RolloutItem {
        RolloutItem::SessionMeta(codex_protocol::protocol::SessionMetaLine {
            meta: codex_protocol::protocol::SessionMeta {
                history_mode,
                ..Default::default()
            },
            git: None,
        })
    }
}
