// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "../RequestId";
import type { RolloutMaintenanceRequestStatus } from "./RolloutMaintenanceRequestStatus";
import type { RolloutMaintenanceSnapshot } from "./RolloutMaintenanceSnapshot";

/**
 * Global snapshots and progress for one request on the receiving connection.
 */
export type RolloutMaintenanceStatusChangedNotification = { "type": "snapshot", status: RolloutMaintenanceSnapshot, } | { "type": "request", requestId: RequestId, status: RolloutMaintenanceRequestStatus, };
