// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolloutMaintenanceActivity } from "./RolloutMaintenanceActivity";

/**
 * Request-local activity. Running does not imply ownership of the global lock.
 */
export type RolloutMaintenanceRequestStatus = { "type": "idle" } | { "type": "queuedForMigration", threadId: string, } | { "type": "waitingForMaintenance", threadId: string | null, owner: RolloutMaintenanceActivity | null, } | { "type": "running", activity: RolloutMaintenanceActivity, };
