// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolloutMaintenanceOperation } from "./RolloutMaintenanceOperation";
import type { RolloutMaintenancePhase } from "./RolloutMaintenancePhase";
import type { RolloutMaintenanceProgress } from "./RolloutMaintenanceProgress";

/**
 * Content-free activity details; counts describe only their named phase.
 */
export type RolloutMaintenanceActivity = { operationId: string, processId: number, operation: RolloutMaintenanceOperation, threadId: string | null, phase: RolloutMaintenancePhase, progress: RolloutMaintenanceProgress | null,
/**
 * Observed bytes handled, including repeated passes; not physical I/O or overall progress.
 */
ioBytes: bigint, };
