// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolloutMaintenanceLockStatus } from "./RolloutMaintenanceLockStatus";
import type { RolloutMaintenanceRequestStatus } from "./RolloutMaintenanceRequestStatus";

/**
 * Current cross-process lock ownership and this server's automatic migration activity.
 */
export type RolloutMaintenanceSnapshot = { lock: RolloutMaintenanceLockStatus,
/**
 * Null when this thread store does not expose an automatic migration worker.
 */
backgroundMigration: RolloutMaintenanceRequestStatus | null, };
