// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolloutMaintenanceActivity } from "./RolloutMaintenanceActivity";

/**
 * The operating-system lock is authoritative; older owners may provide no details.
 */
export type RolloutMaintenanceLockStatus = { "type": "idle" } | { "type": "busy", owner: RolloutMaintenanceActivity | null, };
