// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { InternalChatMessageMetadataPassthrough } from "./InternalChatMessageMetadataPassthrough";
import type { ResponseItemId } from "./ResponseItemId";

export type InterAgentCommunication = { id?: ResponseItemId, author: AgentPath, recipient: AgentPath, other_recipients: Array<AgentPath>, content: string, encrypted_content?: string, internal_chat_message_metadata_passthrough?: InternalChatMessageMetadataPassthrough, trigger_turn: boolean, };
